# Generated by Django 5.1.1 on 2024-10-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_first_name_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_badge',
            field=models.CharField(choices=[('tier_one', 'tier_one'), ('tier_two', 'tier_two'), ('tier_three', 'tier_three'), (None, None)], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
