# Generated by Django 5.1.1 on 2024-11-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userinfo_id_alter_userskill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(default=38.00899),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(default=-1.21999),
        ),
    ]
