# Generated by Django 5.1.1 on 2024-10-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='industry',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
