# Generated by Django 5.1.1 on 2024-10-14 21:09

import datetime
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpSmsToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('otp', models.CharField(default=None, max_length=100, null=True)),
                ('verified', models.BooleanField(default=False, null=True)),
                ('max_otp_tries', models.PositiveIntegerField(default=2, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('otp_try_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_expiry', models.DateTimeField(default=datetime.datetime(2024, 10, 14, 21, 29, 39, 667801, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
