# Generated by Django 5.1.1 on 2024-10-20 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpsmstoken',
            name='date_of_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 22, 50, 33, 620104, tzinfo=datetime.timezone.utc)),
        ),
    ]
