# Generated by Django 5.1.1 on 2024-10-28 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_alter_otpsmstoken_date_of_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpsmstoken',
            name='date_of_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 21, 10, 33, 551390, tzinfo=datetime.timezone.utc)),
        ),
    ]
