# Generated by Django 5.1.1 on 2024-11-03 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_alter_otpsmstoken_date_of_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpsmstoken',
            name='date_of_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 0, 23, 18, 526520, tzinfo=datetime.timezone.utc)),
        ),
    ]
