# Generated by Django 5.1.1 on 2024-11-05 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0025_alter_otpsmstoken_date_of_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpsmstoken',
            name='date_of_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 23, 20, 12, 570040, tzinfo=datetime.timezone.utc)),
        ),
    ]
