# Generated by Django 5.1.1 on 2024-10-23 02:10

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(default=None, max_length=100, unique=True)),
                ('job_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=None, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('one_time', 'One-time')], max_length=20)),
                ('experience_level', models.CharField(choices=[('entry_level', 'Entry Level'), ('mid_level', 'Mid Level'), ('senior', 'Senior')], max_length=20)),
                ('salary_range', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('deadline_date', models.DateTimeField(default=datetime.datetime(2024, 10, 25, 14, 10, 51, 504292, tzinfo=datetime.timezone.utc))),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='jobs.job')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='applied', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='jobs.jobpost')),
                ('reveiwer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedJobPost',
            fields=[
                ('save_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('savedjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_job', to='jobs.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
