# Generated by Django 5.1.1 on 2024-10-23 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 26, 4, 17, 10, 739616, tzinfo=datetime.timezone.utc)),
        ),
    ]
