# Generated by Django 5.1.1 on 2024-10-28 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobpost_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='approval_date',
            field=models.CharField(default=datetime.datetime(2024, 10, 28, 2, 20, 29, 24948, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 14, 20, 29, 24675, tzinfo=datetime.timezone.utc)),
        ),
    ]
