# Generated by Django 5.1.1 on 2024-10-30 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobapplication_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_picture',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='job_pictures'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='approval_date',
            field=models.CharField(default=datetime.datetime(2024, 10, 30, 19, 55, 41, 383338, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 7, 55, 41, 383040, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('one_time', 'One-time')], default='full_time', max_length=20),
        ),
    ]
