# Generated by Django 5.1.1 on 2024-10-31 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_jobapplication_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='approval_date',
            field=models.CharField(default=datetime.datetime(2024, 10, 31, 22, 44, 47, 83480, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 10, 44, 47, 83169, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='SavedJobPost',
        ),
    ]
