# Generated by Django 5.1.1 on 2024-11-01 03:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_jobpost_impressions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='approval_date',
            field=models.CharField(default=datetime.datetime(2024, 11, 1, 3, 12, 46, 765719, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='jobpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='jobs.jobpost'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 15, 12, 46, 765064, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='UserJobPostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_interactions', to='jobs.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_job_interaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('jobpost', 'user')},
            },
        ),
    ]
