# Generated by Django 5.1.1 on 2024-11-05 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_alter_jobapplication_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='approval_date',
            field=models.CharField(default=datetime.datetime(2024, 11, 5, 1, 38, 55, 507885, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 13, 38, 55, 507271, tzinfo=datetime.timezone.utc)),
        ),
    ]
