# Generated by Django 5.1.1 on 2024-11-05 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_jobpost_is_read_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='latitude',
            field=models.FloatField(default=38.00899),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='longitude',
            field=models.FloatField(default=-1.21999),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='approval_date',
            field=models.CharField(default=datetime.datetime(2024, 11, 5, 23, 0, 12, 569269, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 11, 0, 12, 568678, tzinfo=datetime.timezone.utc)),
        ),
    ]
