# Generated by Django 5.1.1 on 2024-11-05 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_jobpost_latitude_jobpost_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='approval_date',
            field=models.CharField(default=datetime.datetime(2024, 11, 5, 23, 5, 19, 929589, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 11, 5, 19, 929007, tzinfo=datetime.timezone.utc)),
        ),
    ]
