# Generated by Django 5.1.1 on 2024-11-07 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_alter_jobapplication_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='comments',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='approval_date',
            field=models.CharField(default=datetime.datetime(2024, 11, 7, 21, 36, 24, 840733, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 10, 9, 36, 24, 840072, tzinfo=datetime.timezone.utc)),
        ),
    ]
