# Generated by Django 5.1.1 on 2024-10-14 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='date_of_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 21, 30, 18, 24147, tzinfo=datetime.timezone.utc)),
        ),
    ]
