# Generated by Django 5.1.1 on 2024-10-23 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0003_alter_passwordresettoken_date_of_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='date_of_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 2, 30, 33, 238415, tzinfo=datetime.timezone.utc)),
        ),
    ]
