# Generated by Django 5.1.1 on 2024-10-31 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0012_alter_passwordresettoken_date_of_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='date_of_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 31, 23, 4, 47, 84486, tzinfo=datetime.timezone.utc)),
        ),
    ]
