# Generated by Django 5.1.1 on 2024-11-03 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0023_alter_passwordresettoken_date_of_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='date_of_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 23, 29, 58, 911905, tzinfo=datetime.timezone.utc)),
        ),
    ]
