# Generated by Django 5.1.1 on 2024-11-06 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0028_alter_passwordresettoken_date_of_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='date_of_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 22, 41, 29, 430535, tzinfo=datetime.timezone.utc)),
        ),
    ]
