# Generated by Django 5.1.1 on 2024-10-23 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('subject', models.CharField(default=None, max_length=150, null=True)),
                ('action', models.CharField(default=None, max_length=100, null=True)),
                ('read_status', models.BooleanField(default=False)),
                ('is_favourite', models.BooleanField(default=False)),
                ('notification_image', models.ImageField(blank=True, max_length=300, null=True, upload_to='profile_pictures')),
                ('notification_category', models.CharField(choices=[('review', 'review'), ('jobpost', 'jobpost'), ('profile_visit', 'profile_visit'), ('new_message', 'new_message')], default='general', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
